-- SQLite
-- UPDATE progress SET location_x = -1700,location_y = -1700 WHERE progress_id = 6;
-- UPDATE progress SET hour = 12 WHERE progress_id = 6;
--SELECT * FROM users;
--DELETE FROM users;
-- SELECT * FROM progress;
-- ALTER TABLE progress ADD COLUMN hour;
